name: super_text_layout_example
description: Super Text Layout example app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  super_text_layout: any

dependency_overrides:
  # Override dependencies within the monorepo. These need to go here otherwise
  # version solving can break when an internal package depends on the pub-hosted
  # version of another internal package, such as how super_editor_markdown
  # depends on super_editor.
  super_text_layout:
    path: ../
  attributed_text:
    path: ../../attributed_text

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
