name: super_editor
repository: https://github.com/superlistapp/super_editor

packages:
  - attributed_text/*
  - super_editor/*
  - super_editor_markdown/*
  - super_text_layout/*
  - website/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze .
  test:
    exec: flutter test -r expanded
    select-package:
      dir-exists: test
