name: super_editor
description: Configurable, composable, extensible text editor and document renderer for Flutter.
version: 0.2.0
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  attributed_text:
    git:
      url: https://github.com/jmatth/super_editor
      path: attributed_text
      ref: main
  characters: ^1.2.0
  collection: ^1.15.0
  http: ^0.13.1
  linkify: ^4.0.0
  logging: ^1.0.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  super_selectable_text:
    git:
      url: https://github.com/jmatth/super_editor
      path: super_selectable_text
      ref: main
  uuid: ^3.0.3

dev_dependencies:
  golden_toolkit: ^0.11.0
  mockito: ^5.0.4

dependency_overrides:
  attributed_text:
    path: ../attributed_text
  super_selectable_text:
    path: ../super_selectable_text

flutter:
  # no Flutter configuration
